----- SCHEME
---- PROJECTS
---Licență 2026
--Roșu Andreea-Florentina


DROP TABLE PROJECTS CASCADE CONSTRAINTS; --da
DROP TABLE TEAM_MEMBERS CASCADE CONSTRAINTS; --da
DROP TABLE TASK_RATES CASCADE CONSTRAINTS;
DROP TABLE TASKS CASCADE CONSTRAINTS; --da
DROP TABLE TEAM_PROJECTS CASCADE CONSTRAINTS; 
DROP TABLE COMMENTS CASCADE CONSTRAINTS; --da
DROP TABLE CHANGE_LOG CASCADE CONSTRAINTS;
DROP TABLE HOLIDAYS_RO CASCADE CONSTRAINTS;

--TABLE 1: PROJECTS
--id_project
--name_project
--description_project
--star_date
--end_date
--total_budget
--real_cost

CREATE TABLE PROJECTS(
    id_project NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name_project VARCHAR2(200) NOT NULL,
    description_project VARCHAR2(2000) NOT NULL,
    star_date DATE NOT NULL,
    end_date DATE NOT NULL,
    fixed_cost NUMBER(10,2) DEFAULT 0 NOT NULL,
    total_budget NUMBER(10,2) DEFAULT 0 NOT NULL,
    real_cost NUMBER(10,2) DEFAULT 0 NOT NULL,
    allocated_budget NUMBER(10,2) DEFAULT 0 NOT NULL,

   CONSTRAINT id_project_pk PRIMARY KEY(id_project)
);


--TABLE 2: TEAM_MEMBERS
--id_member
--name_team_member
--role_member - Manager, SW

CREATE TABLE TEAM_MEMBERS(
    id_member VARCHAR2(7) NOT NULL,
    name_team_member VARCHAR2(60) NOT NULL,
    role_member VARCHAR2(50) NOT NULL,
    hourly_rate NUMBER(10,2) DEFAULT 0 NOT NULL,

    CONSTRAINT id_member_pk PRIMARY KEY(id_member)
);

--TABLE 3: TASK_RATES
--id_rate
--task_type
--hourly_rate
CREATE TABLE TASK_RATES(
    id_rate NUMBER GENERATED BY DEFAULT AS IDENTITY,
    task_type VARCHAR2(50) NOT NULL, --proiectare, implementare, testare
    hourly_rate NUMBER(10,2) NOT NULL,

    CONSTRAINT id_rate_pk PRIMARY KEY(id_rate)
);


--TABLE 4: TASKS
--id_task
--id_project
--title
--description_task
--start_date_task
--end_date_task
--id_predecessor
--priority_task - Low, Medium, High
--status_task
--id_member
--duration

CREATE TABLE TASKS(
    id_task NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_project NUMBER NOT NULL,
    id_task_rate NUMBER NOT NULL,
    id_member VARCHAR2(7),
    title VARCHAR2(60) NOT NULL,
    description_task VARCHAR2(500) NOT NULL,
    start_date_task DATE NOT NULL,
    end_date_task DATE NOT NULL,
    duration NUMBER DEFAULT 1,
    estimated_hours NUMBER DEFAULT 0 NOT NULL,
    actual_hours NUMBER DEFAULT 0 NOT NULL,
    id_predecessor NUMBER,
    priority_task VARCHAR2(10) CHECK (priority_task IN('Low', 'Medium', 'High')),
    status_task VARCHAR2(20) DEFAULT 'Pending' CHECK (status_task IN ('Pending', 'In Progress', 'Completed', 'On Hold', 'Cancelled')),
    

    CONSTRAINT id_task_pk PRIMARY KEY(id_task),
    CONSTRAINT id_project_task_fk FOREIGN KEY (id_project) REFERENCES PROJECTS(id_project),
    CONSTRAINT id_member_task_fk FOREIGN KEY (id_member) REFERENCES TEAM_MEMBERS(id_member),
    CONSTRAINT id_predecessor_task FOREIGN KEY(id_predecessor) REFERENCES TASKS(id_task),
    CONSTRAINT id_rate_task_fk FOREIGN KEY(id_rate) REFERENCES TASK_RATES(id_rate)
);


--TABLE 5: TEAM_PROJECTS
--id_member
--id_project
--date_assign

CREATE TABLE TEAM_PROJECTS(
    id_member VARCHAR2(7),
    id_project NUMBER NOT NULL,
    date_assign DATE DEFAULT SYSDATE, -- =returneaza data si ora curenta

    CONSTRAINT team_projects_pk PRIMARY KEY (id_member, id_project),
    CONSTRAINT team_project_member_fk FOREIGN KEY(id_member) REFERENCES TEAM_MEMBERS(id_member),
    CONSTRAINT team_project_fk FOREIGN KEY(id_project) REFERENCES PROJECTS(id_project)    
);


--TABLE 6: COMMENTS
--id_comment
--id_project
--id_member
--comment_text
--data_comment

CREATE TABLE COMMENTS(
    id_comment NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_project NUMBER NOT NULL,
    id_member VARCHAR2(7) NOT NULL,
    comment_text VARCHAR2(4000) NOT NULL,
    date_comment DATE DEFAULT SYSDATE, -- =returneaza data si ora curenta

    CONSTRAINT id_comment_pk PRIMARY KEY(id_comment),
    CONSTRAINT id_project_comment_fk FOREIGN KEY(id_project) REFERENCES PROJECTS(id_project),
    CONSTRAINT id_member_comment_fk FOREIGN KEY(id_member) REFERENCES TEAM_MEMBERS(id_member)
);


--TABLE 7: CHANGE_LOG
--id_log
--table_name
--id_record --> what id was changed
--action_type --> UPDATE, DELETE
--id_member
--change_date
--column_name --> wich column was changed
--old_value
--new_value

CREATE TABLE CHANGE_LOG(
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY,
    table_name VARCHAR2(30) NOT NULL, 
    id_record NUMBER NOT NULL,
    column_name VARCHAR2(30),
    old_value VARCHAR2(4000),
    new_value VARCHAR2(4000),
    action_type VARCHAR2(30) not null,
    id_member VARCHAR2(7),
    change_date DATE DEFAULT SYSDATE,  -- =returneaza data si ora curenta

    CONSTRAINT id_log_pk PRIMARY KEY(id_log),
    CONSTRAINT id_member__change_log_fk FOREIGN KEY(id_member) REFERENCES TEAM_MEMBERS(id_member)
);


--TABLE 8: HOLIDAYS
--holiday_date
--holiday_name
CREATE TABLE HOLIDAYS_RO(
    holiday_date DATE NOT NULL,
    holiday_name VARCHAR2(100) NOT NULL,

    CONSTRAINT holiday_date_pk PRIMARY KEY(holiday_date)
);


---AUDIT
SELECT 
    cl.table_name AS "Tabel",
    cl.id_record AS "ID Proiect",
    COALESCE(p.name_project, p2.name_project) AS "Nume Proiect",
    cl.column_name AS "Coloana modificată",
    cl.old_value AS "Valoare veche",
    cl.new_value AS "Valoare nouă",
    cl.action_type AS "Acțiune",
    NVL(cl.id_member, 'ADMIN') AS "ID Membru",
    NVL(tm.name_team_member, 'Administrator') AS "Nume Membru",
    cl.change_date AS "Data Modificării"
FROM CHANGE_LOG cl
LEFT JOIN TEAM_MEMBERS tm ON cl.id_member = tm.id_member
LEFT JOIN PROJECTS p ON cl.table_name = 'PROJECTS' AND cl.id_record = p.id_project
LEFT JOIN TASKS t ON cl.table_name = 'TASKS' AND cl.id_record = t.id_task
LEFT JOIN PROJECTS p2 ON t.id_project = p2.id_project